name: Docker Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4
    - name: Build dell'immagine Docker
      run: docker build -t asset-api:test .
